### PR TITLE
Fix typo in description

### PR DESCRIPTION
**Pull request by jkupferer**
Simple typo correction, "creon" -> "cron"

### CODE REVIEW

**Comment by Smiley73** [comment]
Yes the yaml file is auto-generated. I don't think it matters for this change, because the outcome will be the same

**Comment by seanmalloy** [comment]
I don't know for sure. I just want to double check. Please hold on merging this.

**Comment by Smiley73** [comment]
@seanmalloy did you get a chance to look into this?

**Comment by Smiley73** [comment]
Bump

**Pull request merged**
