### PR TITLE
Update operator-sdk to v0.17.1

### LINKED ISSUE #373: Unable to build Eunomia on current version of operator-sdk
**What version of eunomia are you using?**

eunomia version: v0.1.8

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"d7f3ccf9a5bdc96ba92e31526cf014b3de4c46aa", GitTreeState:"clean", BuildDate:"2020-09-16T16:46:07Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

I pulled the latest code base of Eunomia and ran `make build`

**What did you expect to see?**
Eunomia to successfully build

**What did you see instead?**
An error when it was trying to pull all of the necessary dependencies, `github.com/operator-framework/operator-sdk` in particular:
```
$ make build
# Future Item: remove the use of `go mod vendor`
go mod vendor
warning: ignoring symlink $HOME/go/src/github.com/KohlsTechnology/Eunomia/deploy/helm/eunomia-operator/crds
go: github.com/operator-framework/operator-sdk@v0.12.1-0.20191112211508-82fc57de5e5b requires
        github.com/operator-framework/operator-registry@v1.1.1 requires
        bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
make: *** [build] Error 1
```

It seems a dependency of v0.12.1 of the Operator-SDK (bitbucket.org/ww/goautoneg) has been deleted or moved.

### PR DESCRIPTION
**Pull request by vinny-sabatini**
**Description**

* Update the version of the Operator-SDK used for building Eunomia
* Store the Go modules vendor directory in Git so we can rebuild old versions even if dependencies are moved

Fixes #373

**Type of change**

* Bug fix (non-breaking change which fixes an issue)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Checklist**

- [x] Unit tests and e2e tests updated
- [x] Documentation updated

### CODE REVIEW

**Comment by seanmalloy** [comment]
@vinny-sabatini the changes look good. I think we should also add a CI check to ensure that the `vendor` directory is in sync with `go.mod` and `go.sum`. I believe we can accomplish this by just adding the command `go mod vendor` to the `test-dirty` target in the `Makefile`.

Can you make this change in this PR?

**Comment by vinny-sabatini** [comment]
@seanmalloy I have amended my second commit (10e8428) to add the check to the `test-dirty` Make target.

**Review by seanmalloy — APPROVED** [review]
LGTM

**Comment by seanmalloy** [comment]
This should be safe to merge once all the CI tests pass.

**Pull request merged**
