### PR TITLE
Operator util integration

### LINKED ISSUE #23: Operator Best Practices Refactor
## What happens?

We can simplify our code by leveraging the `operator-utils` library.

## What were you expecting to happen?

Leverage https://github.com/redhat-cop/operator-utils to simplify code.

## Steps to reproduce: 

n/a

## Any errors, stacktrace, logs? 

n/a

## Environment:

* Runtime version(Java, Go, Python, etc): n/a
* Desktop OS/version: n/a

## Additional comments:

none

### PR DESCRIPTION
**Pull request by raffaelespazzoli**
# Pull Request Template

## Description

this PR integrates eunomia with the [operator-utils](https://github.com/redhat-cop/operator-utils) library.
the objectives of this library are:
1. enforce some best practices when developing operators
2. provide some common-use utility functions 

The advantages for eunomia in adopting this library are:
1. less code to maintain
2. more readable code (especially in the reconcile cycle)
3. basic status management
4. basic error management
5. basic event management

Fixes #23 

## Type of change

* Refactoring

### CODE REVIEW

**Comment by seanmalloy** [comment]
@raffaelespazzoli we planning on completing this work between 7/18 and 8/1.

**Comment by raffaelespazzoli** [comment]
@seanmalloy I am stuck on this issue: https://github.com/kubernetes-sigs/controller-runtime/issues/524
for some reason I am hitting it. The code port is complete but the unit tests don't work. Any help would be appreciated.

**Comment by seanmalloy** [comment]
@raffaelespazzoli thanks for the info. this is in scope for our next sprint which starts 7/18, so we will try to figure it out.

**Comment by Smiley73** [comment]
What's the latest in this issue? Can we get this wrapped up?

**Comment by seanmalloy** [comment]
It is assigned to @bjaroszewski. We will remove this from the 0.0.1 milestone if we do not have a resolution soon.

**Comment by seanmalloy** [comment]
This pull request is currently on hold.

**Comment by seanmalloy** [comment]
There are many conflicts now. We will not be merging this. Closing for now.

**Pull request closed without merging**
