### PR TITLE
run operator as non-root user inside container

### PR DESCRIPTION
**Pull request by seanmalloy**
## Description

Make sure the operator does not run as root when running in a container.

## Type of change

Please delete options that are not relevant.

* Bug fix (non-breaking change which fixes an issue)

## Environment

* Runtime version(Java, Go, Python, etc): Go Lang 1.12.x

### CODE REVIEW

**Comment by seanmalloy** [comment]
I did not test this yet, but I am using this setup for a different project which is working. Please do not merge yet.

**Comment by Smiley73** [comment]
What's the latest in this issue? Can we get this wrapped up?

**Comment by seanmalloy** [comment]
I still have not had a chance to test this. If someone else has sometime to test this that would be super helpful.

**Comment by Smiley73** [comment]
@seanmalloy  this PR is good. Unit tests, e2e, and full cluster-seed example all passed.

**Pull request merged**
