### PR TITLE
Fix helm release automation

### LINKED ISSUE #166: Release Automation Fails to Build Helm Charts
**What version of eunomia are you using?**

eunomia version: v0.0.4

**Does this issue reproduce with the latest release?**

Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

n/a

**What did you do?**

After creating the Eunomia v0.0.4 release the helm chart build automation that is executed by Travis CI failed to completed successfully.

**What did you expect to see?**

I expected the helm charts for the eunomia v0.0.4 release to be pushed to the gh-pages branch.

**What did you see instead?**

Here is the relevant output from the Travis CI log. The full log are be found here, https://api.travis-ci.com/v3/job/259263304/log.txt.
```
./scripts/build/publish-chart-repo.sh
+mkdir -p /tmp/helm/publish
+git -C /tmp/helm/publish clone -b gh-pages git@github.com:KohlsTechnology/eunomia.git .
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.

+version=v0.0.4
+envsubst
+helm lint deploy/helm/eunomia-operator
2019/11/21 22:44:59 found symbolic link in path: /home/travis/gopath/src/github.com/KohlsTechnology/eunomia/deploy/helm/eunomia-operator/crds resolves to /home/travis/gopath/src/github.com/KohlsTechnology/eunomia/deploy/crds
==> Linting deploy/helm/eunomia-operator
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
++basename deploy/helm/eunomia-operator
+chart_dest=/tmp/helm/publish/eunomia-operator
+mkdir -p /tmp/helm/publish/eunomia-operator
+helm package -d /tmp/helm/publish/eunomia-operator deploy/helm/eunomia-operator
2019/11/21 22:44:59 found symbolic link in path: /home/travis/gopath/src/github.com/KohlsTechnology/eunomia/deploy/helm/eunomia-operator/crds resolves to /home/travis/gopath/src/github.com/KohlsTechnology/eunomia/deploy/crds
Successfully packaged chart and saved it to: /tmp/helm/publish/eunomia-operator/eunomia-operator-v0.0.4.tgz
Error: stat /home/travis/.helm/repository/local: no such file or directory
Makefile:70: recipe for target 'publish-chart-repo' failed
make: *** [publish-chart-repo] Error 1
Script failed with status 2

travis_fold:end:dpl.3
failed to deploy
```

### PR DESCRIPTION
**Pull request by karolkrawczyk**
**Description**

Run helm init --client-only in order to create helm client 
files directory in home directory.

Fixes #166 

**Type of change**

* Bug fix (non-breaking change which fixes an issue)

**Checklist**

- [not needed ] Unit tests and e2e tests updated
- [not needed] Documentation updated

### CODE REVIEW

**Comment by karolkrawczyk** [comment]
Unfortunatelly, I wasn't able to reproduce the issue on my local environment. 
I believe that proposed change will fix the issue, as per https://github.com/helm/helm/issues/1732 it looks like no helm commands are guaranteed to work without running helm init first.   

@seanmalloy do you have any suggestion how this issue can be tested?

**Comment by seanmalloy** [comment]
I think the only way to test would be to fork the repo and do a release from the fork to see what happens. You would have to change a few things to make the release automation work correctly from the fork. Exactly what those "few things" are would need some tinkering to exactly figure out.

**Comment by seanmalloy** [comment]
@karolkrawczyk let me know if you need help testing this.

**Comment by karolkrawczyk** [comment]
After some tinkering I was able to run travis CI on my forked branch. Helm client files will be created in home directory as shown below:
```
+helm init --client-only
Creating /home/travis/.helm 
Creating /home/travis/.helm/repository 
Creating /home/travis/.helm/repository/cache 
Creating /home/travis/.helm/repository/local 
Creating /home/travis/.helm/plugins 
Creating /home/travis/.helm/starters 
Creating /home/travis/.helm/cache/archive 
Creating /home/travis/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /home/travis/.helm.
Not installing Tiller due to 'client-only' flag having been set
+version=v999.0.0
+envsubst
+helm lint deploy/helm/eunomia-operator
2020/01/21 14:42:21 found symbolic link in path: /home/travis/gopath/src/github.com/KohlsTechnology/eunomia/deploy/helm/eunomia-operator/crds resolves to /home/travis/gopath/src/github.com/KohlsTechnology/eunomia/deploy/crds
==> Linting deploy/helm/eunomia-operator
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
++basename deploy/helm/eunomia-operator
+chart_dest=/tmp/helm/publish/eunomia-operator
+mkdir -p /tmp/helm/publish/eunomia-operator
+helm package -d /tmp/helm/publish/eunomia-operator deploy/helm/eunomia-operator
2020/01/21 14:42:21 found symbolic link in path: /home/travis/gopath/src/github.com/KohlsTechnology/eunomia/deploy/helm/eunomia-operator/crds resolves to /home/travis/gopath/src/github.com/KohlsTechnology/eunomia/deploy/crds
Successfully packaged chart and saved it to: /tmp/helm/publish/eunomia-operator/eunomia-operator-v999.0.0.tgz
++dirname KohlsTechnology/eunomia
++basename KohlsTechnology/eunomia
+helm repo index --url https://KohlsTechnology.github.io/eunomia /tmp/helm/publish
```
The job doesn't fail anymore on helm related operations. Link to full log https://api.travis-ci.com/v3/job/277952338/log.txt

I was also able to reproduce the issue in travis. Link to log for run without command `helm --client-only`:  https://api.travis-ci.com/v3/job/277954496/log.txt

**Pull request merged**
